---
title: "KENYA CONTINUOUS HOUSEHOLD SURVEY PROGRAMME (KCHSP) 2022"
format: html
editor: Source
---

## SUMMARY

1. Roster information = individuals_microdata.dta
 - No info on pregnancy and/or lactating women 
 - No info on who's eating at home (days and/or meals)
 - Variables starting from
        - "d" seemed related to employment: d52 - how much you pay to go to work and d53 - how far Km is work
        - "c" seemed related to education (attendance)
        -
 
2. Food consumption = food_items_microdata.dta
 - Info on food consumed provided in Kg/L (not specified)

**Assumption**:
From the Kenya Continuous Household Survey Programme (KCHSP) 2021. Interviewers' Manual (KNBS, 2021). In litre : 401, 405, 406, 402, 404, 403, 407, 409, 411, 507, 905, 907, 1202, 1204, 1205, 1601, 1602, 1603, 1701, 1702, 1703, 1504, 1505.


### Breastfeeding 

#### Note: exclusive breastfeeding up to 5 months was 60% (DHS, 2022). 

U.S. Department of Agriculture and U.S. Department of
Health and Human Services. Dietary Guidelines for Americans, 2020-2025.
9th Edition. December 2020. Available at DietaryGuidelines.gov. 

### Pregnancy 

Prevalence was 5.5% according to the latest DHS (2022) (See Table 5.2 Fertility by background characteristics). 

### Infants breasfeeding practices

Based on the latest DHS (2022, See Table 11.4 Breastfeeding status according to age).

Exclusive breastfeeding
0–1 months = 77.2%
2–3 months = 60.8%
4–5 months = 38.0%


Continued breastfeeding
12–15 months 85.1%  
16–19 months 66.2%  
20–23 months 42.7% 


## Note on lactating women & Energy calculation function

There are three options:
1. There is a variable that identify which women is lactating (e.g. info is provided in the survey).
2. The lactating women is assumed based on having a lactating child base on mother and child relation to the head of the household (e.g. info is provided to relationship , eg. mother/spouse and son/daughter, daughter and grandchild).
3. The lactating women is assumed based on one child at the household is < 24months of age.


## Traditional Vegetables 

Traditional vegetables (713) are according to the documentation (REF).

"Fresh Assorted leaves, commonly grown subsistently. Are a variety, namely; pumpkin leaves, pigweed, mchicha, kunde, managu, spider plant (saga, isagek) etc.

UOM: Kilogram"
